Complete crud functions in AppUserService.java
beedofficial/beed-backend pull request #34
Opened 2023-12-03 13:32 UTC by CemalettinCelalToy

delete user, update user, and create user functions  have been added

2023-12-03 15:56 UTC, shintalha requested changes
servis katmanındaki try catchlerde exception yakalanıp tekrar throw edilmiş, onlar silinebilir, şimdilik servis katmanında try catch yapmayalımdiye düşündüm, controller kısmında yaparız, ben örneğini yaptım, kodu pushlayınca görünebilecek

2023-12-03 15:56 UTC, shintalha commented on src/main/java/com/beed/service/AppUserService.java
> +            throw new Exception(ex.getMessage());
Kanka burada catchleyip tekrar throw edilmiş, try catchleri controller katmanında yaparz diye düşünmüştüm, o yüzden methodun yanında throws Exception yazıp metodun içinde dümdüz işini yapabilirsin

2023-12-03 15:56 UTC, shintalha commented on src/main/java/com/beed/service/AppUserService.java
> +            throw new Exception(ex.getMessage());
Sanırım diğerlerinde de aynısı olmuş, onları düzeltebiliriz istersen, burada şimdilik try catch koymayalım ben de koymadım

2023-12-03 20:12 UTC, mertcarabaci commented
LGTM!

2023-12-05 10:19 UTC, shintalha approved these changes
Eline sağlık :)

2023-12-05 10:19 UTC, merged